# Generated by Django 3.2.9 on 2021-11-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_skill_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_skill', to='jobs.job'),
        ),
    ]
