# Generated by Django 3.2.9 on 2021-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_skill_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
